---
application:
  name: "get-reddit-comments-test"
  project: "get_com1"
  organization: "QoveryCommunity"
  storage:
  - name: "teststorage"
    size: "10"
    type: "ssd"
    mount_point: "/mnt/teststorage"
routers:
- name: "main-get-reddit-comments-test"
  routes:
  - application_name: "get-reddit-comments-test"
    paths:
    - "/*"
