---
application:
  name: "get-reddit-comments"
  project: "get comments"
  organization: "QoveryCommunity"
  storage:
  - name: "db"
    size: "500"
    type: "hdd"
    mount_point: "/mnt/db"
routers:
- name: "main-get-reddit-comments"
  routes:
  - application_name: "get-reddit-comments"
    paths:
    - "/*"
